name: deal_o_round
description: Flutter port of the originally PlayN based Deal-O-Round game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.22+22

environment:
  sdk: ">=2.25.0"
  flutter: ">=3.13.0-0.2.pre"

dependencies:
  games_services: ^3.0.2
  get: ^4.6.5
  intl: ^0.18.1
  assets_audio_player: ^3.1.1
  shared_preferences: ^2.2.1
  soundpool: ^2.4.1
  spinner_input_plus: ^0.0.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.14
  wakelock_plus: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cards
      fonts:
        - asset: fonts/cards.ttf
    - family: Musicals
      fonts:
        - asset: fonts/musicals.ttf
    - family: Roboto-Condensed
      fonts:
        - asset: fonts/roboto-condensed.ttf
    - family: Stint-Ultra-Condensed
      fonts:
        - asset: fonts/stint-ultra-condensed.ttf
