name: deal_o_round
description: Flutter port of the originally PlayN based Deal-O-Round game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.7+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audioplayers: ^0.19.0
  games_services: ^2.0.0-nullsafety.3
  get: ^4.1.4
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  soundpool: ^2.1.0
  spinner_input:
    git:
      url: https://github.com/CsabaConsulting/spinner_input.git
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.6
  wakelock: ^0.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cards
      fonts:
        - asset: fonts/cards.ttf
    - family: Musicals
      fonts:
        - asset: fonts/musicals.ttf
    - family: Roboto-Condensed
      fonts:
        - asset: fonts/roboto-condensed.ttf
    - family: Stint-Ultra-Condensed
      fonts:
        - asset: fonts/stint-ultra-condensed.ttf
